# Generated by Django 3.2.8 on 2021-10-25 18:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=80)),
                ('data_vencimento', models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 25, 15, 29, 0, 192086), null=True)),
                ('valor', models.FloatField()),
                ('data_pagamento', models.DateTimeField(blank=True, default=None, null=True)),
                ('recorrente', models.BooleanField(blank=True, default=False, null=True)),
                ('paga', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
    ]
